export enum OrganizationAppTypes {

  ZENDESK_SUPPORT = 'ZENDESK_SUPPORT',
  ZENDESK_SELL = 'ZENDESK_SELL',
  ZENDESK_SUNSHINE = 'ZENDESK_SUNSHINE',
  GOCARDLESS = 'GOCARDLESS',
  STRIPE = 'STRIPE',
  PIPEDRIVE = 'PIPEDRIVE',
  SENDGRID = 'SENDGRID',
  TWILIO_SMS = 'TWILIO_SMS',
}
