import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import {
    SchemaColumnValidatorEnums,
    SchemaColumnValidatorTypes,
} from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';

export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'Type',
        label: 'type',
        description: 'The type of project',
        type: SchemaColumnTypes.ENUM,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        options: [],
        validators: [],
    },
    {
        name: 'Description',
        label: 'description',
        description: 'The description of the project',
        type: SchemaColumnTypes.TEXT_LONG,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        options: [],
        validators: [],
    },
    {
        name: 'EstimatedStartDate',
        label: 'estimated start',
        description: 'the estimated start date of the project',
        type: SchemaColumnTypes.DATE,
        position: 1,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'EstimatedEndDate',
        label: 'estimated end',
        description: 'the estimated end date of the project',
        type: SchemaColumnTypes.DATE,
        position: 2,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'ActualStartDate',
        label: 'actual start',
        description: 'system generated when the project is moved out of the first stage of the pipeline',
        type: SchemaColumnTypes.DATE,
        position: 3,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'ActualEndDate',
        label: 'actual end',
        description: 'system generated when the project is moved to the selected success stage of the pipeline',
        type: SchemaColumnTypes.DATE,
        position: 4,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'Cost',
        label: 'cost',
        description: 'A system generated value aggregating the cost of all related child milestones',
        type: SchemaColumnTypes.CURRENCY,
        position: 5,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'CostOverride',
        label: 'cost override',
        description: 'A user generated value takes priority over the aggregated cost',
        type: SchemaColumnTypes.CURRENCY,
        position: 6,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'MilestoneTotalCount',
        label: 'milestone total count',
        description: 'A system generated count of all child milestones',
        type: SchemaColumnTypes.NUMBER,
        position: 7,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name ],
    },
    {
        name: 'MilestoneCompleteCount',
        label: 'milestone complete count',
        description: 'A system generated count of all child milestones completed',
        type: SchemaColumnTypes.NUMBER,
        position: 8,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name ],
    },
    {
        name: 'MilestoneFailCount',
        label: 'milestone fail count',
        description: 'A system generated count of all child milestones failed',
        type: SchemaColumnTypes.NUMBER,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name ],
    },
    {
        name: 'PolygonId',
        label: 'polygon id',
        description: 'Polygon id for the task',
        type: SchemaColumnTypes.NUMBER,
        position: 12,
        isStatic: false,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name, SchemaColumnValidatorEnums.REQUIRED ],
    },
];
