export enum ORGANIZATION_USER_RBAC_PERMISSION_TYPE {
  COLUMN = 'COLUMN',
  SCHEMA = 'SCHEMA',
  USER = 'USER',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  GROUP = 'GROUP',
  API = 'API',
  PIPELINE = 'PIPELINE',
  TOKEN = 'TOKEN',
  DB_RECORD = 'DB_RECORD',
}
