import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import { SchemaColumnValidatorTypes } from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';

export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'IssuedDate',
        label: 'issue date',
        description: 'the date the order is issued',
        type: SchemaColumnTypes.DATE,
        position: 2,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: null,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'DeliveryDate',
        label: 'delivery date',
        description: 'the date the order is delivered',
        type: SchemaColumnTypes.DATE,
        position: 3,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: null,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'BillingStartDate',
        label: 'billing start date',
        description: 'Billing start date',
        type: SchemaColumnTypes.DATE,
        position: 4,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: null,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'BillingTerms',
        label: 'billing terms',
        description: 'Billing terms i.e NET 15,30',
        type: SchemaColumnTypes.ENUM,
        position: 5,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 'NET_0',
        options: [
            { label: 'NET 0', value: 'NET_0', position: 0 },
            { label: 'NET 3', value: 'NET_3', position: 1 },
            { label: 'NET 10', value: 'NET_10', position: 2 },
            { label: 'NET 15', value: 'NET_15', position: 3 },
            { label: 'NET 30', value: 'NET_30', position: 4 },
            { label: 'NET 60', value: 'NET_60', position: 5 },
            { label: 'NET 90', value: 'NET_90', position: 6 },
            { label: 'NET 120', value: 'NET_120', position: 7 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'Subtotal',
        label: 'subtotal',
        description: 'subtotal of the prices no taxes',
        type: SchemaColumnTypes.CURRENCY,
        position: 6,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'TotalDiscounts',
        label: 'total discounts',
        description: 'total discounts',
        type: SchemaColumnTypes.CURRENCY,
        position: 7,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'TotalTaxAmount',
        label: 'total tax amount',
        description: 'total taxes',
        type: SchemaColumnTypes.CURRENCY,
        position: 8,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'TotalPrice',
        label: 'total price',
        description: 'total price including taxes and discounts',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'TaxRate',
        label: 'tax rate',
        description: 'unit cost for the product derived from product components UnitCost',
        type: SchemaColumnTypes.PERCENT,
        position: 10,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_PERCENT.name ],
    },
    {
        name: 'VATNumber',
        label: 'vat number',
        description: 'VAT Number',
        type: SchemaColumnTypes.TEXT,
        position: 11,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.TEXT.name ],
    },
    {
        name: 'CurrencyCode',
        description: 'Currency code',
        type: SchemaColumnTypes.ENUM,
        position: 12,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 'GBP',
        options: [
            { label: 'GBP', value: 'GBP', position: 0 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'RequestedDeliveryDate',
        label: 'requested delivery date',
        description: 'the delivery date requested by the customer',
        type: SchemaColumnTypes.DATE,
        position: 14,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'DiscountValue',
        label: 'discount value',
        description: 'the value to discount',
        type: SchemaColumnTypes.CURRENCY,
        position: 15,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'DiscountType',
        label: 'discount type',
        description: 'the type of discount',
        type: SchemaColumnTypes.ENUM,
        position: 16,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 'AMOUNT',
        options: [
            { label: 'Amount', value: 'AMOUNT', position: 0 },
            { label: 'Percent', value: 'PERCENT', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.TEXT.name ],
    },
    {
        name: 'UDPRN',
        label: 'udprn',
        description: 'unique delivery point reference number',
        type: SchemaColumnTypes.NUMBER,
        position: 17,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name ],
    },
    {
        name: 'UMPRN',
        label: 'umprn',
        description: 'unique multiple point reference number',
        type: SchemaColumnTypes.NUMBER,
        position: 18,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name ],
    },
    {
        name: 'TransferPhone',
        label: 'transfer phone',
        description: 'phone number to transfer',
        type: SchemaColumnTypes.PHONE_NUMBER,
        position: 19,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.PHONE.name ],
    },

];
