export const GET_GROUPS_DATA_REQUEST = 'GET_GROUPS_DATA_REQUEST';
export const GET_GROUPS_DATA_SUCCESS = 'GET_GROUPS_DATA_SUCCESS';
export const GET_GROUPS_DATA_ERROR = 'GET_GROUPS_DATA_ERROR';

export const SET_ASSIGN_GROUPS_MODAL_VISIBLE = 'SET_ASSIGN_GROUPS_MODAL_VISIBLE';

export const GET_GROUP_BY_ID_REQUEST = 'GET_GROUP_BY_ID_REQUEST';
export const GET_GROUP_BY_ID_SUCCESS = 'GET_GROUP_BY_ID_SUCCESS';
export const GET_GROUP_BY_ID_ERROR = 'GET_GROUP_BY_ID_ERROR';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';

export const ASSIGN_USERS_TO_GROUP_REQUEST = 'ASSIGN_USERS_TO_GROUP_REQUEST';
export const ASSIGN_USERS_TO_GROUP_SUCCESS = 'ASSIGN_USERS_TO_GROUP_SUCCESS';
export const ASSIGN_USERS_TO_GROUP_ERROR = 'ASSIGN_USERS_TO_GROUP_ERROR';
