import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import {
    SchemaColumnValidatorEnums,
    SchemaColumnValidatorTypes,
} from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';

export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'Description',
        label: 'description',
        description: 'description of the order item',
        type: SchemaColumnTypes.TEXT,
        position: 1,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'DiscountValue',
        label: 'discount value',
        description: 'the value to discount',
        type: SchemaColumnTypes.CURRENCY,
        position: 3,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'DiscountType',
        label: 'discount type',
        description: 'the type of discount',
        type: SchemaColumnTypes.ENUM,
        position: 4,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 'AMOUNT',
        options: [
            { label: 'Amount', value: 'AMOUNT', position: 0 },
            { label: 'Percent', value: 'PERCENT', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'Quantity',
        description: 'quantity item',
        type: SchemaColumnTypes.NUMBER,
        position: 6,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 1,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'TaxRate',
        description: 'tax rate for the item',
        type: SchemaColumnTypes.NUMBER,
        position: 6,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'Taxable',
        description: 'is the item taxable',
        type: SchemaColumnTypes.ENUM,
        position: 7,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'YES',
        options: [
            { label: 'Yes', value: 'YES', position: 0 },
            { label: 'No', value: 'NO', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'TaxIncluded',
        description: 'is tax included in the UnitPrice',
        type: SchemaColumnTypes.ENUM,
        position: 8,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'YES',
        options: [
            { label: 'Yes', value: 'YES', position: 0 },
            { label: 'No', value: 'NO', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'UnitPrice',
        label: 'unit price',
        description: 'suggested retail price cost + markup',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'TotalTaxes',
        label: 'total taxes',
        description: 'total taxes for the line item',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'TotalDiscounts',
        label: 'total discounts',
        description: 'total discounts for the line item',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'TotalPrice',
        label: 'total price',
        description: '(unit price - total discounts) + taxes ',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'ActivationStatus',
        label: 'activation status',
        description: 'status of the order item (must be closed for billing)',
        type: SchemaColumnTypes.ENUM,
        position: 10,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isStatusColumn: true,
        defaultValue: 'OPEN',
        options: [
            { label: 'Open', value: 'OPEN', position: 0 }, // Order Management has not completed any fulfillment lines.
            { label: 'Closed', value: 'CLOSED', position: 1 }, // Order Management completed all fulfillment lines.
            { label: 'Cancelled', value: 'CANCELLED', position: 2 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'NextBillingDate',
        label: 'next billing date',
        description: 'the next date the item will be charged',
        type: SchemaColumnTypes.DATE,
        position: 11,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorEnums.DATE ],
    },
    {
        name: 'NextInvoiceDate',
        label: 'next invoice date',
        description: 'the next date the item will appear on an invoice',
        type: SchemaColumnTypes.DATE,
        position: 12,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorEnums.DATE ],
    },
    {
        name: 'BillingPeriodType',
        label: 'billing period type',
        description: 'the billing period for the item',
        type: SchemaColumnTypes.ENUM,
        position: 13,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: true,
        options: [
            { label: 'Free', value: 'FREE', position: 0 },
            { label: 'Discount', value: 'DISCOUNT', position: 1 },
            { label: 'Standard', value: 'STANDARD', position: 2 },
        ],
    },
    {
        name: 'ProductRef',
        label: 'item reference',
        description: 'id of the product',
        type: SchemaColumnTypes.UUID,
        position: 14,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorEnums.UUID ],
    },
    {
        name: 'ProductType',
        label: 'product type',
        description: 'the type of product',
        type: SchemaColumnTypes.TEXT,
        position: 15,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorEnums.TEXT ],
    },
    {
        name: 'ProductCategory',
        label: 'product category',
        description: 'the type of category',
        type: SchemaColumnTypes.TEXT,
        position: 16,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorEnums.TEXT ],
    },

];
