import {
    RBAC_DEFAULT_PERMISSION_GROUPS_CREATE,
    RBAC_DEFAULT_PERMISSION_GROUPS_DELETE,
    RBAC_DEFAULT_PERMISSION_GROUPS_GET,
    RBAC_DEFAULT_PERMISSION_GROUPS_SEARCH,
    RBAC_DEFAULT_PERMISSION_GROUPS_UPDATE,
    RBAC_DEFAULT_PERMISSION_PERMISSIONS_CREATE,
    RBAC_DEFAULT_PERMISSION_PERMISSIONS_DELETE,
    RBAC_DEFAULT_PERMISSION_PERMISSIONS_GET,
    RBAC_DEFAULT_PERMISSION_PERMISSIONS_SEARCH,
    RBAC_DEFAULT_PERMISSION_PERMISSIONS_UPDATE,
    RBAC_DEFAULT_PERMISSION_PIPELINES_CREATE,
    RBAC_DEFAULT_PERMISSION_PIPELINES_DELETE,
    RBAC_DEFAULT_PERMISSION_PIPELINES_GET,
    RBAC_DEFAULT_PERMISSION_PIPELINES_SEARCH,
    RBAC_DEFAULT_PERMISSION_PIPELINES_UPDATE,
    RBAC_DEFAULT_PERMISSION_ROLES_CREATE,
    RBAC_DEFAULT_PERMISSION_ROLES_DELETE,
    RBAC_DEFAULT_PERMISSION_ROLES_GET,
    RBAC_DEFAULT_PERMISSION_ROLES_SEARCH,
    RBAC_DEFAULT_PERMISSION_ROLES_UPDATE,
    RBAC_DEFAULT_PERMISSION_SCHEMAS_CREATE,
    RBAC_DEFAULT_PERMISSION_SCHEMAS_DELETE,
    RBAC_DEFAULT_PERMISSION_SCHEMAS_GET,
    RBAC_DEFAULT_PERMISSION_SCHEMAS_SEARCH,
    RBAC_DEFAULT_PERMISSION_SCHEMAS_UPDATE,
    RBAC_DEFAULT_PERMISSION_TOKEN_CREATE,
    RBAC_DEFAULT_PERMISSION_TOKEN_DELETE,
    RBAC_DEFAULT_PERMISSION_TOKEN_GET,
    RBAC_DEFAULT_PERMISSION_TOKEN_SEARCH,
    RBAC_DEFAULT_PERMISSION_TOKEN_UPDATE,
    RBAC_DEFAULT_PERMISSION_USERS_CREATE,
    RBAC_DEFAULT_PERMISSION_USERS_DELETE,
    RBAC_DEFAULT_PERMISSION_USERS_GET,
    RBAC_DEFAULT_PERMISSION_USERS_SEARCH,
    RBAC_DEFAULT_PERMISSION_USERS_UPDATE,
}                         from '../../permissions/types/RBACDefaultPermissions';
import { RBACRoleCreate } from './RBACRoleCreate';

export const RBAC_DEFAULT_ROLES: Array<RBACRoleCreate> = [
    {

        name: 'users.admin',
        description: 'OrganizationUserEntity has full control over users',
        permissions: [

            RBAC_DEFAULT_PERMISSION_USERS_SEARCH,
            RBAC_DEFAULT_PERMISSION_USERS_GET,
            RBAC_DEFAULT_PERMISSION_USERS_CREATE,
            RBAC_DEFAULT_PERMISSION_USERS_UPDATE,
            RBAC_DEFAULT_PERMISSION_USERS_DELETE

        ]
    },
    {

        name: 'roles.admin',
        description: 'OrganizationUserEntity has full control over roles',
        permissions: [

            RBAC_DEFAULT_PERMISSION_ROLES_SEARCH,
            RBAC_DEFAULT_PERMISSION_ROLES_GET,
            RBAC_DEFAULT_PERMISSION_ROLES_CREATE,
            RBAC_DEFAULT_PERMISSION_ROLES_UPDATE,
            RBAC_DEFAULT_PERMISSION_ROLES_DELETE

        ]
    },
    {

        name: 'permissions.admin',
        description: 'OrganizationUserEntity has full control over permissions',
        permissions: [

            RBAC_DEFAULT_PERMISSION_PERMISSIONS_SEARCH,
            RBAC_DEFAULT_PERMISSION_PERMISSIONS_GET,
            RBAC_DEFAULT_PERMISSION_PERMISSIONS_CREATE,
            RBAC_DEFAULT_PERMISSION_PERMISSIONS_UPDATE,
            RBAC_DEFAULT_PERMISSION_PERMISSIONS_DELETE

        ]
    },
    {

        name: 'groups.admin',
        description: 'OrganizationUserEntity has full control over groups',
        permissions: [

            RBAC_DEFAULT_PERMISSION_GROUPS_SEARCH,
            RBAC_DEFAULT_PERMISSION_GROUPS_GET,
            RBAC_DEFAULT_PERMISSION_GROUPS_CREATE,
            RBAC_DEFAULT_PERMISSION_GROUPS_UPDATE,
            RBAC_DEFAULT_PERMISSION_GROUPS_DELETE

        ]
    },
    {

        name: 'schemas.admin',
        description: 'OrganizationUserEntity has full control over schemas.',
        permissions: [

            RBAC_DEFAULT_PERMISSION_SCHEMAS_SEARCH,
            RBAC_DEFAULT_PERMISSION_SCHEMAS_GET,
            RBAC_DEFAULT_PERMISSION_SCHEMAS_CREATE,
            RBAC_DEFAULT_PERMISSION_SCHEMAS_UPDATE,
            RBAC_DEFAULT_PERMISSION_SCHEMAS_DELETE

        ]
    }, {

        name: 'pipelines.admin',
        description: 'OrganizationUserEntity has full control over pipelines.',
        permissions: [

            RBAC_DEFAULT_PERMISSION_PIPELINES_SEARCH,
            RBAC_DEFAULT_PERMISSION_PIPELINES_GET,
            RBAC_DEFAULT_PERMISSION_PIPELINES_CREATE,
            RBAC_DEFAULT_PERMISSION_PIPELINES_UPDATE,
            RBAC_DEFAULT_PERMISSION_PIPELINES_DELETE

        ]
    },
    {
        name: 'tokens.admin',
        description: 'OrganizationUserEntity has full control over tokens.',
        permissions: [
            RBAC_DEFAULT_PERMISSION_TOKEN_CREATE,
            RBAC_DEFAULT_PERMISSION_TOKEN_DELETE,
            RBAC_DEFAULT_PERMISSION_TOKEN_UPDATE,
            RBAC_DEFAULT_PERMISSION_TOKEN_GET,
            RBAC_DEFAULT_PERMISSION_TOKEN_SEARCH,
        ]
    }

];
