export const SEND_CONFIRMATION_EMAIL_REQUEST = 'SEND_CONFIRMATION_EMAIL_REQUEST';
export const SEND_CONFIRMATION_EMAIL_SUCCESS = 'SEND_CONFIRMATION_EMAIL_SUCCESS';
export const SEND_CONFIRMATION_EMAIL_ERROR = 'SEND_CONFIRMATION_EMAIL_ERROR';
