import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import { SchemaColumnValidatorEnums } from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';

export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'Feature',
        label: 'feature',
        description: 'The feature',
        type: SchemaColumnTypes.ENUM,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        options: [
            { label: 'Blockage desilt', value: 'BLOCKAGE_DESILT', position: 0 },
            { label: 'Blockage standard first', value: 'BLOCKAGE_STANDARD_FIRST', position: 1 },
            { label: 'Blockage standard next', value: 'BLOCKAGE_STANDARD_NEXT', position: 2 },
            { label: 'Cable access', value: 'CABLE_ACCESS', position: 3 },
            { label: 'Cable distribution', value: 'CABLE_DISTRIBUTION', position: 4 },
            { label: 'Cable drop', value: 'CABLE_DROP', position: 5 },
            { label: 'Cable feed', value: 'CABLE_FEED', position: 5 },
            { label: 'Cable spine', value: 'CABLE_SPINE', position: 5 },
            { label: 'Chamber CW1', value: 'CHAMBER_CW1', position: 5 },
            { label: 'Chamber CW2', value: 'CHAMBER_CW2', position: 5 },
            { label: 'Chamber FW2', value: 'CHAMBER_FW2', position: 5 },
            { label: 'Chamber FW4', value: 'CHAMBER_FW4', position: 5 },
            { label: 'Chamber FW6', value: 'CHAMBER_FW6', position: 5 },
            { label: 'Closure L0', value: 'CLOSURE_L0', position: 5 },
            { label: 'Closure L1', value: 'CLOSURE_L1', position: 5 },
            { label: 'Closure L2', value: 'CLOSURE_L2', position: 5 },
            { label: 'Closure L3', value: 'CLOSURE_L3', position: 5 },
            { label: 'Closure L4', value: 'CLOSURE_L4', position: 5 },
            { label: 'Duct', value: 'DUCT', position: 5 },
            { label: 'Duct lead in', value: 'DUCT_LEAD_IN', position: 5 },
            { label: 'Duct sub duct', value: 'DUCT_SUB_DUCT', position: 5 },
            { label: 'Pole', value: 'POLE', position: 5 },
            { label: 'Rope', value: 'ROPE', position: 5 },
            { label: 'Closure', value: 'CLOSURE', position: 5 },
            { label: 'Cable', value: 'CABLE', position: 5 },
        ],
        validators: [ SchemaColumnValidatorEnums.REQUIRED ],
    },
    {
        name: 'Type',
        label: 'type',
        description: 'The type of feature',
        type: SchemaColumnTypes.ENUM,
        position: 1,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        options: [
            { label: 'Default', value: 'DEFAULT', position: 0 },
            { label: 'L0', value: 'L0', position: 1 },
            { label: 'L1', value: 'L1', position: 2 },
            { label: 'L2', value: 'L2', position: 3 },
            { label: 'L3', value: 'L3', position: 4 },
            { label: 'L4', value: 'L4', position: 5 },
        ],
        validators: [ SchemaColumnValidatorEnums.REQUIRED ],
    },
    {
        name: 'Description',
        label: 'description',
        description: 'The description of the feature',
        type: SchemaColumnTypes.TEXT_LONG,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        options: [],
        validators: [],
    },
    {
        name: 'ExternalRef',
        label: 'external ref',
        description: 'The external id of the feature',
        type: SchemaColumnTypes.NUMBER,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        options: [],
        validators: [],
    },
];
