export const ELASTIC_SEARCH_CLIENT = 'ELASTIC_SEARCH_CLIENT';
export const ELASTIC_SEARCH_LOGS_CLIENT = 'ELASTIC_SEARCH_LOGS_CLIENT';
export const S3_BUCKET_NAME_FOR_ORG_FILES = process.env.S3_BUCKET_NAME_FOR_ORG_FILES||'odin-org-files-71231b3e-7996-474e-a66b-2dc2ba907799';

