import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import { SchemaColumnValidatorTypes } from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';

export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'DisplayName',
        label: 'display name',
        description: 'display name of the discount for marketing materials',
        type: SchemaColumnTypes.TEXT,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: true,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.UNIQUE.name,
        ],
    },
    {
        name: 'Description',
        label: 'description',
        description: 'description of the discount',
        type: SchemaColumnTypes.TEXT,
        position: 1,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'Code',
        label: 'code',
        description: 'code to redeem this discount ex. 10OFF',
        type: SchemaColumnTypes.TEXT,
        position: 2,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.UNIQUE.name,
        ],
    },
    {
        name: 'DiscountValue',
        label: 'discount value',
        description: 'the value to discount',
        type: SchemaColumnTypes.CURRENCY,
        position: 3,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name, SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'DiscountType',
        label: 'discount type',
        description: 'the type of discount',
        type: SchemaColumnTypes.ENUM,
        position: 4,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'AMOUNT',
        options: [
            { label: 'Amount', value: 'AMOUNT', position: 0 },
            { label: 'Percent', value: 'PERCENT', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'DiscountUnit',
        label: 'discount unit',
        description: 'discount duration unit',
        type: SchemaColumnTypes.ENUM,
        position: 5,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'MONTHS',
        options: [
            { label: 'Month', value: 'MONTHS', position: 1 },
            { label: 'Days', value: 'DAYS', position: 2 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'DiscountLength',
        label: 'discount length',
        description: 'length for the items discount duration',
        type: SchemaColumnTypes.NUMBER,
        position: 6,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [ 'REQUIRED' ],
    },
    {
        name: 'TrialUnit',
        label: 'trial unit',
        description: 'trial unit for the discount',
        type: SchemaColumnTypes.ENUM,
        position: 7,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'MONTHS',
        options: [
            { label: 'Month', value: 'MONTHS', position: 1 },
            { label: 'Days', value: 'DAYS', position: 2 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'TrialLength',
        label: 'trial length',
        description: 'trial length for the discount',
        type: SchemaColumnTypes.NUMBER,
        position: 8,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'AvailableFrom',
        description: 'the discount is available from this date',
        type: SchemaColumnTypes.DATE_TIME,
        position: 9,
        isStatic: true,
        isHidden: false,
        validators: [ SchemaColumnValidatorTypes.DATE_TIME.name ],
    },
    {
        name: 'AvailableTo',
        description: 'ths discount is available to this date',
        type: SchemaColumnTypes.DATE_TIME,
        position: 10,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorTypes.DATE_TIME.name ],
    },
];

