import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import { SchemaColumnValidatorTypes } from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';


export const columns: SchemaColumnCreateUpdateDto[] = [

    {
        name: 'Type',
        label: 'type',
        description: 'Type of address (Shipping, Billing)',
        type: SchemaColumnTypes.ENUM,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        options: [
            { label: 'Shipping', value: 'SHIPPING', position: 0 },
            { label: 'Billing', value: 'BILLING', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'FullAddress',
        label: 'full address',
        description: 'The full address.',
        type: SchemaColumnTypes.TEXT,
        position: 2,
        isStatic: true,
        isHidden: false,
        isTitleColumn: true,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name, SchemaColumnValidatorTypes.TEXT.name ],
    },
    {
        name: 'AddressLine1',
        label: 'address line 1',
        description: 'The first line of the contacts address.',
        type: SchemaColumnTypes.TEXT,
        position: 3,
        isStatic: true,
        isHidden: false,
        isTitleColumn: true,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name, SchemaColumnValidatorTypes.TEXT.name ],
    }, {
        name: 'AddressLine2',
        label: 'address line 2',
        description: 'The second line of the contacts address.',
        type: SchemaColumnTypes.TEXT,
        position: 4,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.TEXT.name ],
    },
    {
        name: 'AddressLine3',
        label: 'address line 3',
        description: 'The third line of the contacts address.',
        type: SchemaColumnTypes.TEXT,
        position: 5,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.TEXT.name ],
    },
    {
        name: 'City',
        label: 'city',
        description: 'The city of the contacts address.',
        type: SchemaColumnTypes.TEXT,
        position: 6,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name, SchemaColumnValidatorTypes.TEXT.name ],
    },
    {
        name: 'PostalCode',
        label: 'postal code',
        description: 'The postal code of the contacts address.',
        type: SchemaColumnTypes.TEXT,
        position: 7,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name, SchemaColumnValidatorTypes.TEXT.name ],
    },
    {
        name: 'CountryCode',
        label: 'country code',
        description: 'The country code of the contact (GB)',
        type: SchemaColumnTypes.TEXT,
        position: 8,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 'GB',
        options: [
            { label: 'Great Britain', value: 'GB', position: 0 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'SalesStatus',
        label: 'sales status',
        description: 'The sales status for the address',
        type: SchemaColumnTypes.TEXT,
        position: 9,
        isStatic: false,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: '',
        options: [
            { label: 'Register Interest', value: 'REGISTER_INTEREST', position: 0 },
            { label: 'Pre-Order', value: 'PRE_ORDER', position: 0 },
            { label: 'Order', value: 'ORDER', position: 0 },
        ],
        validators: [],
    },
    {
        name: 'UDPRN',
        label: 'udprn',
        description: 'The Unique Delivery Point Reference Number',
        type: SchemaColumnTypes.NUMBER,
        position: 10,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.UNIQUE.name,
            SchemaColumnValidatorTypes.NUMBER.name,
        ],
    },
    {
        name: 'UMPRN',
        label: 'umprn',
        description: 'The Unique Multiple Premise Reference Number',
        type: SchemaColumnTypes.NUMBER,
        position: 11,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.UNIQUE.name,
            SchemaColumnValidatorTypes.NUMBER.name,
        ],
    },
];
