export const formFields = [
  {
    label: '',
    property: 'id',
    type: 'TEXT',
    isRequired: true,
    message: '',
    isHidden: true,
    value: undefined,
  },
  {
    label: 'Name',
    property: 'name',
    type: 'TEXT',
    isRequired: true,
    message: 'Please input Name',
    isHidden: false,
    value: undefined,
  },
  {
    label: 'Base Url',
    property: 'baseUrl',
    type: 'TEXT',
    isRequired: true,
    message: 'Please input Base Url',
    isHidden: false,
    value: undefined,
  },
  {
    label: 'API key',
    property: 'apiKey',
    type: 'TEXT',
    isRequired: true,
    message: 'Please input API key',
    isHidden: false,
    value: undefined,
  },
]
