import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import { SchemaColumnValidatorTypes } from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';


export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'Status',
        label: 'Status',
        description: 'status of the invoice',
        type: SchemaColumnTypes.ENUM,
        position: 1,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: true,
        defaultValue: 'DRAFT',
        options: [
            { label: 'Draft', value: 'DRAFT', position: 0 },
            { label: 'Approval Pending', value: 'APPROVAL_PENDING', position: 1 },
            { label: 'Pending', value: 'PENDING', position: 2 },
            { label: 'Partial', value: 'PARTIAL', position: 3 },
            { label: 'Payment Pending', value: 'PAYMENT_PENDING', position: 4 },
            { label: 'Paid', value: 'PAID', position: 5 },
            { label: 'Error', value: 'ERROR', position: 6 },
            { label: 'Void', value: 'VOID', position: 7 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'IssuedDate',
        label: 'issue date',
        description: 'the date the order is issued',
        type: SchemaColumnTypes.DATE,
        position: 2,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: true,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'DueDate',
        label: 'due date',
        description: 'invoice due date',
        type: SchemaColumnTypes.DATE,
        position: 3,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: null,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.DATE.name,
        ],
    },
    {
        name: 'BillingTerms',
        label: 'billing terms',
        description: 'Billing terms i.e NET 15,30',
        type: SchemaColumnTypes.ENUM,
        position: 4,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 'NET_0',
        options: [
            { label: 'NET 0', value: 'NET_0', position: 0 },
            { label: 'NET 3', value: 'NET_3', position: 1 },
            { label: 'NET 10', value: 'NET_10', position: 2 },
            { label: 'NET 15', value: 'NET_15', position: 3 },
            { label: 'NET 30', value: 'NET_30', position: 4 },
            { label: 'NET 60', value: 'NET_60', position: 5 },
            { label: 'NET 90', value: 'NET_90', position: 6 },
            { label: 'NET 120', value: 'NET_120', position: 7 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'Subtotal',
        label: 'subtotal',
        description: 'subtotal of the prices no taxes',
        type: SchemaColumnTypes.CURRENCY,
        position: 5,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'TotalDiscounts',
        label: 'total discounts',
        description: 'total discounts',
        type: SchemaColumnTypes.CURRENCY,
        position: 6,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'TotalTaxAmount',
        label: 'total tax amount',
        description: 'total taxes',
        type: SchemaColumnTypes.CURRENCY,
        position: 7,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'TotalDue',
        label: 'total due',
        description: 'total due including taxes and discounts',
        type: SchemaColumnTypes.CURRENCY,
        position: 8,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: true,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'Balance',
        label: 'balance',
        description: 'balance left to be paid',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: true,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'TaxRate',
        label: 'tax rate',
        description: 'unit cost for the product derived from product components UnitCost',
        type: SchemaColumnTypes.PERCENT,
        position: 10,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_PERCENT.name ],
    },
    {
        name: 'VATNumber',
        label: 'vat number',
        description: 'VAT Number',
        type: SchemaColumnTypes.TEXT,
        position: 11,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.TEXT.name ],
    },
    {
        name: 'CurrencyCode',
        description: 'Currency code',
        type: SchemaColumnTypes.ENUM,
        position: 12,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 'GBP',
        options: [
            { label: 'GBP', value: 'GBP', position: 0 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'DiscountValue',
        label: 'discount value',
        description: 'the value to discount',
        type: SchemaColumnTypes.CURRENCY,
        position: 13,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'DiscountType',
        label: 'discount type',
        description: 'the type of discount',
        type: SchemaColumnTypes.ENUM,
        position: 14,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 'AMOUNT',
        options: [
            { label: 'Amount', value: 'AMOUNT', position: 0 },
            { label: 'Percent', value: 'PERCENT', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.TEXT.name ],
    },
];

