export const GET_TOKENS_DATA_REQUEST = 'GET_TOKENS_DATA_REQUEST';
export const GET_TOKENS_DATA_SUCCESS = 'GET_TOKENS_DATA_SUCCESS';
export const GET_TOKENS_DATA_ERROR = 'GET_TOKENS_DATA_ERROR';

export const DELETE_TOKEN_REQUEST = 'DELETE_TOKEN_REQUEST';
export const DELETE_TOKEN_SUCCESS = 'DELETE_TOKEN_SUCCESS';
export const DELETE_TOKEN_ERROR = 'DELETE_TOKEN_ERROR';

export const CREATE_TOKEN_REQUEST = 'CREATE_TOKEN_REQUEST';
export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS';
export const CREATE_TOKEN_ERROR = 'CREATE_TOKEN_ERROR';

export const GET_TOKEN_BY_ID_REQUEST = 'GET_TOKEN_BY_ID_REQUEST';
export const GET_TOKEN_BY_ID_SUCCESS = 'GET_TOKEN_BY_ID_SUCCESS';
export const GET_TOKEN_BY_ID_ERROR = 'GET_TOKEN_BY_ID_ERROR';