export const GET_USERS_DATA_REQUEST = 'GET_USERS_DATA_REQUEST';
export const GET_USERS_DATA_SUCCESS = 'GET_USERS_DATA_SUCCESS';
export const GET_USERS_DATA_ERROR = 'GET_USERS_DATA_ERROR';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_ERROR = 'GET_USER_BY_ID_ERROR';

export const ASSIGN_ROLES_TO_USER_REQUEST = 'ASSIGN_ROLES_TO_USER_REQUEST';
export const ASSIGN_ROLES_TO_USER_SUCCESS = 'ASSIGN_ROLES_TO_USER_SUCCESS';
export const ASSIGN_ROLES_TO_USER_ERROR = 'ASSIGN_ROLES_TO_USER_ERROR';

export const ASSIGN_GROUPS_TO_USER_REQUEST = 'ASSIGN_GROUPS_TO_USER_REQUEST';
export const ASSIGN_GROUPS_TO_USER_SUCCESS = 'ASSIGN_GROUPS_TO_USER_SUCCESS';
export const ASSIGN_GROUPS_TO_USER_ERROR = 'ASSIGN_GROUPS_TO_USER_ERROR';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

export const EDIT_USER_PASSWORD_REQUEST = 'EDIT_USER_PASSWORD_REQUEST';
export const EDIT_USER_PASSWORD_SUCCESS = 'EDIT_USER_PASSWORD_SUCCESS';
export const EDIT_USER_PASSWORD_ERROR = 'EDIT_USER_PASSWORD_ERROR';

export const SET_ASSIGN_USER_MODAL_VISIBLE = 'SET_ASSIGN_USER_MODAL_VISIBLE';

export const GET_ORGANIZATION_BY_ID_DATA_REQUEST = 'GET_ORGANIZATION_BY_ID_DATA_REQUEST';
export const GET_ORGANIZATION_BY_ID_DATA_SUCCESS = 'GET_ORGANIZATION_BY_ID_DATA_SUCCESS';
export const GET_ORGANIZATION_BY_ID_DATA_ERROR = 'GET_ORGANIZATION_BY_ID_DATA_ERROR';

export const SAVE_ORGANIZATION_DATA_REQUEST = 'SAVE_ORGANIZATION_DATA_REQUEST';
export const SAVE_ORGANIZATION_DATA_SUCCESS = 'SAVE_ORGANIZATION_DATA_SUCCESS';
export const SAVE_ORGANIZATION_DATA_ERROR = 'SAVE_ORGANIZATION_DATA_ERROR';