version: '3'

services:
    template:
        build:
            context: .
        hostname:       'dev'
        container_name: odin-api-template
        env_file:
           - .env
        ports:
            - 10106:80
        networks:
            odin_network:
                ipv4_address: 99.0.0.106
        volumes:
            - ./src:/app/src
            - /app/node_modules

networks:
    odin_network:
        external: true

