export const GET_CONNECTED_APPS_DATA_REQUEST = 'GET_CONNECTED_APPS_DATA_REQUEST';
export const GET_CONNECTED_APPS_DATA_SUCCESS = 'GET_CONNECTED_APPS_DATA_SUCCESS';
export const GET_CONNECTED_APPS_DATA_ERROR = 'GET_CONNECTED_APPS_DATA_ERROR';

export const DELETE_CONNECTED_APP_REQUEST = 'DELETE_CONNECTED_APP_REQUEST';
export const DELETE_CONNECTED_APP_SUCCESS = 'DELETE_CONNECTED_APP_SUCCESS';
export const DELETE_CONNECTED_APP_ERROR = 'DELETE_CONNECTED_APP_ERROR';

export const CREATE_CONNECTED_APP_REQUEST = 'CREATE_CONNECTED_APP_REQUEST';
export const CREATE_CONNECTED_APP_SUCCESS = 'CREATE_CONNECTED_APP_SUCCESS';
export const CREATE_CONNECTED_APP_ERROR = 'CREATE_CONNECTED_APP_ERROR';

export const GET_CONNECTED_APP_BY_ID_REQUEST = 'GET_CONNECTED_APP_BY_ID_REQUEST';
export const GET_CONNECTED_APP_BY_ID_SUCCESS = 'GET_CONNECTED_APP_BY_ID_SUCCESS';
export const GET_CONNECTED_APP_BY_ID_ERROR = 'GET_CONNECTED_APP_BY_ID_ERROR';

export const EDIT_CONNECTED_APP_REQUEST = 'EDIT_CONNECTED_APP_REQUEST';
export const EDIT_CONNECTED_APP_SUCCESS = 'EDIT_CONNECTED_APP_SUCCESS';
export const EDIT_CONNECTED_APP_ERROR = 'EDIT_CONNECTED_APP_ERROR';