export const GET_PERMISSIONS_DATA_REQUEST = 'GET_PERMISSIONS_DATA_REQUEST';
export const GET_PERMISSIONS_DATA_SUCCESS = 'GET_PERMISSIONS_DATA_SUCCESS';
export const GET_PERMISSIONS_DATA_ERROR = 'GET_PERMISSIONS_DATA_ERROR';

export const SET_ASSIGN_PERMISSIONS_MODAL_VISIBLE = 'SET_ASSIGN_PERMISSIONS_MODAL_VISIBLE';

export const CREATE_PERMISSION_REQUEST = 'CREATE_PERMISSION_REQUEST';
export const CREATE_PERMISSION_SUCCESS = 'CREATE_PERMISSION_SUCCESS';
export const CREATE_PERMISSION_ERROR = 'CREATE_PERMISSION_ERROR';

export const GET_PERMISSION_BY_ID_REQUEST = 'GET_PERMISSION_BY_ID_REQUEST';
export const GET_PERMISSION_BY_ID_SUCCESS = 'GET_PERMISSION_BY_ID_SUCCESS';
export const GET_PERMISSION_BY_ID_ERROR = 'GET_PERMISSION_BY_ID_ERROR';

export const DELETE_PERMISSION_REQUEST = 'DELETE_PERMISSION_REQUEST';
export const DELETE_PERMISSION_SUCCESS = 'DELETE_PERMISSION_SUCCESS';
export const DELETE_PERMISSION_ERROR = 'DELETE_PERMISSION_ERROR';

export const ASSIGN_ROLES_TO_PERMISSION_REQUEST = 'ASSIGN_ROLES_TO_PERMISSION_REQUEST';
export const ASSIGN_ROLES_TO_PERMISSION_SUCCESS = 'ASSIGN_ROLES_TO_PERMISSION_SUCCESS';
export const ASSIGN_ROLES_TO_PERMISSION_ERROR = 'ASSIGN_ROLES_TO_PERMISSION_ERROR';
