import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import {
    SchemaColumnValidatorEnums,
    SchemaColumnValidatorTypes,
} from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';

export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'Type',
        label: 'type',
        description: 'The type of task',
        type: SchemaColumnTypes.ENUM,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        options: [
            { label: 'Splice', value: 'SPLICE', position: 0 },
            { label: 'Test', value: 'TEST', position: 1 },
            { label: 'Pull', value: 'PULL', position: 2 },
            { label: 'Blow', value: 'BLOW', position: 3 },
            { label: 'Deploy', value: 'DEPLOY', position: 4 },
            { label: 'Admin', value: 'ADMIN', position: 5 },
            { label: 'Plan', value: 'PLAN', position: 6 },
            { label: 'Survey', value: 'SURVEY', position: 7 },
            { label: 'Design', value: 'DESIGN', position: 8 },
            { label: 'Clear', value: 'CLEAR', position: 9 },
        ],
        validators: [],
    },
    {
        name: 'Category',
        label: 'category',
        description: 'The category of task',
        type: SchemaColumnTypes.ENUM,
        position: 1,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        options: [
            { label: 'Closure', value: 'CLOSURE', position: 0 },
            { label: 'Chamber', value: 'CHAMBER', position: 1 },
            { label: 'Pole', value: 'POLE', position: 2 },
            { label: 'Cable', value: 'CABLE', position: 6 },
            { label: 'Duct', value: 'DUCT', position: 7 },
            { label: 'Rope', value: 'ROPE', position: 8 },
            { label: 'As-built', value: 'AS_BUILT', position: 9 },
            { label: 'Reservation', value: 'RESERVATION', position: 10 },
            { label: 'Default', value: 'DEFAULT', position: 10 },
        ],
        validators: [],
    },
    {
        name: 'PIANOI',
        label: 'PIANOI',
        description: '',
        type: SchemaColumnTypes.TEXT,
        position: 1,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        options: [],
        validators: [
            SchemaColumnValidatorEnums.TEXT,
        ],
    },
    {
        name: 'Description',
        label: 'description',
        description: 'The description of the task',
        type: SchemaColumnTypes.TEXT_LONG,
        position: 2,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        options: [],
        validators: [],
    },
    {
        name: 'Position',
        label: 'position',
        description: 'The position of the task',
        type: SchemaColumnTypes.NUMBER,
        position: 3,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        options: [],
        validators: [
            SchemaColumnValidatorEnums.NUMBER,
        ],
    },
    {
        name: 'ExternalRef',
        label: 'external refer',
        description: 'The external reference id',
        type: SchemaColumnTypes.TEXT,
        position: 4,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        options: [],
        validators: [
            SchemaColumnValidatorEnums.TEXT,
        ],
    },
    {
        name: 'EstimatedStartDate',
        label: 'estimated start',
        description: 'the estimated start date of the task',
        type: SchemaColumnTypes.DATE,
        position: 4,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'EstimatedEndDate',
        label: 'estimated end',
        description: 'the estimated end date of the task',
        type: SchemaColumnTypes.DATE,
        position: 5,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'ActualStartDate',
        label: 'actual start',
        description: 'system generated when the task is moved out of the first stage of the pipeline',
        type: SchemaColumnTypes.DATE,
        position: 6,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'ActualEndDate',
        label: 'actual end',
        description: 'system generated when the task is moved to the selected success stage of the pipeline',
        type: SchemaColumnTypes.DATE,
        position: 7,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: null,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'Cost',
        label: 'cost',
        description: 'A system generated value aggregating the cost of all related child tasks',
        type: SchemaColumnTypes.CURRENCY,
        position: 8,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'CostOverride',
        label: 'cost override',
        description: 'A user generated value takes priority over the aggregated cost',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'SubtaskTotalCount',
        label: 'subtask total count',
        description: 'A system generated count of all child subtasks',
        type: SchemaColumnTypes.NUMBER,
        position: 10,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name ],
    },
    {
        name: 'SubtaskCompleteCount',
        label: 'subtask complete count',
        description: 'A system generated count of all child subtasks completed',
        type: SchemaColumnTypes.NUMBER,
        position: 11,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name ],
    },
    {
        name: 'SubtaskFailCount',
        label: 'subtask fail count',
        description: 'A system generated count of all child subtasks failed',
        type: SchemaColumnTypes.NUMBER,
        position: 12,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name ],
    },
    {
        name: 'PolygonId',
        label: 'polygon id',
        description: 'Polygon id for the task',
        type: SchemaColumnTypes.NUMBER,
        position: 12,
        isStatic: false,
        isHidden: false,
        isTitleColumn: false,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER.name, SchemaColumnValidatorEnums.REQUIRED ],
    },
];
