export const UPDATE_MAP_STATE = 'UPDATE_MAP_STATE';
export const UPDATE_MAP_COORDINATES_STATE = 'UPDATE_MAP_COORDINATES_STATE';
export const SET_MAP_SEARCH_QUERY = 'SET_MAP_SEARCH_QUERY';
export const RESET_MAP_SEARCH_QUERY = 'RESET_MAP_SEARCH_QUERY';