export const CREATE_ORDER_MODAL_VISIBILE = 'CREATE_ORDER_MODAL_VISIBILE';

export const SELECT_ORDER_TYPE_MODAL_VISIBILE = 'SELECT_ORDER_TYPE_MODAL_VISIBILE';

export const UPDATE_ORDER_WORKFLOW = 'UPDATE_ORDER_WORKFLOW';

export const ORDER_WORKFOLOW_CHECKOUT_REQUEST = 'ORDER_WORKFOLOW_CHECKOUT_REQUEST';
export const ORDER_WORKFOLOW_CHECKOUT_SUCCESS = 'ORDER_WORKFOLOW_CHECKOUT_SUCCESS';
export const ORDER_WORKFOLOW_CHECKOUT_ERROR = 'ORDER_WORKFOLOW_CHECKOUT_ERROR';
