version: '3'

services:
    template:
        build:
            context: .
        hostname: 'docker'
        container_name: odin-api-settings
        env_file:
           - .env
        environment:
            LOCAL_PORT: 80
            REDIS_ENDPOINT: odin-redis
            REDIS_PORT: 6379
        ports:
            - 10116:80
        networks:
            odin_network:
                ipv4_address: 99.0.0.116
        volumes:
            - ./src:/app/src
            - /app/node_modules
networks:
    odin_network:
        external: true

