import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import {
    SchemaColumnValidatorEnums,
    SchemaColumnValidatorTypes,
} from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';


export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'Description',
        label: 'description',
        description: 'item description',
        type: SchemaColumnTypes.TEXT,
        position: 0,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        validators: [],
    },
    {
        name: 'Type',
        label: 'component type',
        description: 'type of component',
        type: SchemaColumnTypes.ENUM,
        position: 1,
        isStatic: false,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'DATA',
        options: [
            { label: 'Broadband', value: 'BROADBAND', position: 0 },
            { label: 'Voice', value: 'VOICE', position: 1 },
            { label: 'Labor', value: 'LABOR', position: 3 },
            { label: 'Material', value: 'MATERIAL', position: 4 },
        ],
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
        ],
    },
    {
        name: 'UnitPrice',
        label: 'unit price',
        description: 'unit price for the item',
        type: SchemaColumnTypes.CURRENCY,
        position: 2,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'UnitCost',
        label: 'unit cost',
        description: 'unit cost for the item',
        type: SchemaColumnTypes.CURRENCY,
        position: 3,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'UnitType',
        label: 'unit type',
        description: 'unit of measure the product',
        type: SchemaColumnTypes.ENUM,
        position: 4,
        isStatic: false,
        isHidden: false,
        isTitleColumn: false,
        options: [
            { label: 'Per Unit', value: 'UNIT', position: 0 },
            { label: 'Per Linear Meter', value: 'LINEAR_METER', position: 4 },
            { label: 'Per 100 Meter', value: '100_METER', position: 5 },
        ],
        validators: [
            SchemaColumnValidatorEnums.REQUIRED,
        ],
    },
    {
        name: 'IsBillable',
        label: 'item description',
        description: 'if billable is true this will be billable to the end customer',
        type: SchemaColumnTypes.BOOLEAN,
        position: 5,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: true,
        validators: [ SchemaColumnValidatorEnums.REQUIRED ],
    },
    {
        name: 'AvailableFrom',
        label: 'available from',
        description: 'item is available from this date',
        type: SchemaColumnTypes.DATE,
        position: 5,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.DATE.name,
        ],
    },
    {
        name: 'AvailableTo',
        label: 'available to',
        description: 'item is available to this date',
        type: SchemaColumnTypes.DATE,
        position: 6,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorTypes.DATE.name ],
    },
    {
        name: 'MinimumSalePrice',
        label: 'minimum sale price',
        description: 'minimum sale price of the product components default is UnitCost',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'InStockQuantity',
        label: 'in stock quantity',
        description: 'quantity in stock',
        type: SchemaColumnTypes.NUMBER,
        position: 27,
        isStatic: true,
        isHidden: true,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorEnums.NUMBER ],
    },
    {
        name: 'Quantity',
        label: 'quantity',
        description: 'quantity is used when used with Product__ProductComponent relation',
        type: SchemaColumnTypes.NUMBER,
        position: 28,
        isStatic: true,
        isHidden: true,
        isVisibleInTables: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorEnums.NUMBER ],
    },
    {
        name: 'RequiresProvisioning',
        label: 'Requires provisioning',
        description: 'does the product require service provisioning',
        type: SchemaColumnTypes.ENUM,
        position: 21,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        options: [
            { label: 'Yes', value: 'YES', position: 0 },
            { label: 'No', value: 'NO', position: 1 },
        ],
        validators: [ SchemaColumnValidatorEnums.REQUIRED ],
    },
    {
        name: 'RequiresOnSiteSetup',
        label: 'Requires on-site setup',
        description: 'does the product require on-site setup',
        type: SchemaColumnTypes.ENUM,
        position: 22,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        options: [
            { label: 'Yes', value: 'YES', position: 0 },
            { label: 'No', value: 'NO', position: 1 },
        ],
        validators: [ SchemaColumnValidatorEnums.REQUIRED ],
    },
    {
        name: 'Retrievable',
        label: 'retrievable',
        description: 'retrievable product (leased, rented)',
        type: SchemaColumnTypes.ENUM,
        position: 22,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'NO',
        options: [
            { label: 'Yes', value: 'YES', position: 0 },
            { label: 'No', value: 'NO', position: 1 },
        ],
        validators: [
            SchemaColumnValidatorEnums.REQUIRED,
        ],
    },
    {
        name: 'Shippable',
        label: 'Shippable',
        description: 'can the product be shipped to the end customer',
        type: SchemaColumnTypes.ENUM,
        position: 23,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        options: [
            { label: 'Yes', value: 'YES', position: 0 },
            { label: 'No', value: 'NO', position: 1 },
        ],
        validators: [ SchemaColumnValidatorEnums.REQUIRED ],
    },
];

