import { SchemaColumnCreateUpdateDto } from '@d19n/models/dist/schema-manager/schema/column/dto/schema.column.create.update.dto';
import { SchemaColumnTypes } from '@d19n/models/dist/schema-manager/schema/column/types/schema.column.types';
import { SchemaColumnValidatorTypes } from '@d19n/models/dist/schema-manager/schema/column/validator/schema.column.validator.types';

export const columns: SchemaColumnCreateUpdateDto[] = [
    {
        name: 'Description',
        label: 'description',
        description: 'description of the order item',
        type: SchemaColumnTypes.TEXT,
        position: 1,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'UnitPrice',
        label: 'unit price',
        description: 'suggested retail price cost + markup',
        type: SchemaColumnTypes.CURRENCY,
        position: 2,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'DiscountValue',
        label: 'discount value',
        description: 'the value to discount',
        type: SchemaColumnTypes.CURRENCY,
        position: 3,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.NUMBER_CURRENCY.name ],
    },
    {
        name: 'DiscountType',
        label: 'discount type',
        description: 'the type of discount',
        type: SchemaColumnTypes.ENUM,
        position: 4,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 'AMOUNT',
        options: [
            { label: 'Amount', value: 'AMOUNT', position: 0 },
            { label: 'Percent', value: 'PERCENT', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'Quantity',
        description: 'quantity item',
        type: SchemaColumnTypes.NUMBER,
        position: 5,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 1,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'TaxRate',
        description: 'tax rate for the item',
        type: SchemaColumnTypes.NUMBER,
        position: 6,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'Taxable',
        description: 'is the item taxable',
        type: SchemaColumnTypes.ENUM,
        position: 7,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'YES',
        options: [
            { label: 'Yes', value: 'YES', position: 0 },
            { label: 'No', value: 'NO', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'TaxIncluded',
        description: 'is tax included in the UnitPrice',
        type: SchemaColumnTypes.ENUM,
        position: 8,
        isStatic: true,
        isHidden: false,
        isTitleColumn: false,
        defaultValue: 'YES',
        options: [
            { label: 'Yes', value: 'YES', position: 0 },
            { label: 'No', value: 'NO', position: 1 },
        ],
        validators: [ SchemaColumnValidatorTypes.REQUIRED.name ],
    },
    {
        name: 'TotalPrice',
        label: 'total price',
        description: 'total price for the line item',
        type: SchemaColumnTypes.CURRENCY,
        position: 9,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        defaultValue: 0,
        validators: [
            SchemaColumnValidatorTypes.REQUIRED.name,
            SchemaColumnValidatorTypes.NUMBER_CURRENCY.name,
        ],
    },
    {
        name: 'ProductRef',
        label: 'item reference',
        description: 'id of the product',
        type: SchemaColumnTypes.UUID,
        position: 10,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        validators: [ SchemaColumnValidatorTypes.UUID.name ],
    },
    {
        name: 'BillingPeriodType',
        label: 'billing period type',
        description: 'the billing period for the item',
        type: SchemaColumnTypes.ENUM,
        position: 12,
        isStatic: true,
        isHidden: true,
        isTitleColumn: false,
        isVisibleInTables: true,
        options: [
            { label: 'Free', value: 'FREE', position: 0 },
            { label: 'Discount', value: 'DISCOUNT', position: 1 },
            { label: 'Standard', value: 'STANDARD', position: 2 },
        ],
    },
];

