export const INITIALIZE_SHARED_FORM = 'INITIALIZE_SHARED_FORM';

export const CLOSE_SHARED_FORM_MODAL = 'CLOSE_SHARED_FORM_MODAL';

export const UPDATE_SHARED_FORM_INPUT = 'UPDATE_SHARED_FORM_INPUT';
