export const GET_DB_RECORD_AUDIT_LOGS_REQUEST = 'GET_DB_RECORD_AUDIT_LOGS_REQUEST';
export const GET_DB_RECORD_AUDIT_LOGS_SUCCESS = 'GET_DB_RECORD_AUDIT_LOGS_SUCCESS';
export const GET_DB_RECORD_AUDIT_LOGS_ERROR = 'GET_DB_RECORD_AUDIT_LOGS_ERROR';

